alias l='ls -lt -h'
alias cp='cp -v'
alias mv='mv -v'
alias rm='rm -I -v'
alias cx='cd ..'
alias suspend='sudo pm-suspend'
alias poweroff='sudo poweroff'
alias ta='xfce4-taskmanager'

alias fk='xmodmap ~/.xmodmaprc && nohup xcompmgr -c -f -C -F -S -r10 -D4 -t 50 &'

alias ppp='make html && make publish && cd output/ && gup && cx'
alias gup='git add -A && git commit -a -m 'update' && git push origin master'

alias antlr4='java -jar /usr/local/lib/antlr-4.0-complete.jar'
alias antlr3='java -jar /usr/local/lib/antlr-3.5.1-complete.jar'
alias antlrworks='java -jar /usr/local/lib/antlrworks-1.4.3.jar'
alias grun='java org.antlr.v4.runtime.misc.TestRig'

alias eclipse='nohup ~/eclipse/eclipse &'

export JAVA_HOME=/usr/lib/jvm/java-7-sun  
export JRE_HOME=${JAVA_HOME}/jre  
export CLASSPATH=.:${JAVA_HOME}/lib:${JRE_HOME}/lib  
export PATH=${JAVA_HOME}/bin:$PATH 
export CLASSPATH=".:/usr/local/lib/antlr-4.2-complete.jar:$CLASSPATH"
export CLASSPATH=".:/usr/local/lib/antlr-3.5.1-complete.jar:$CLASSPATH"
